package genotp

import (
	"bytes"
	"sort"
	"strings"
)

const maxContextFieldLen = 256

const (
	DistanceClassSameArea = "same_area"
	DistanceClassNearby   = "nearby"
	DistanceClassFar      = "far"
)

var allowedDistanceClasses = map[string]struct{}{
	DistanceClassSameArea: {},
	DistanceClassNearby:   {},
	DistanceClassFar:      {},
}

type OtpContext struct {
	bytes []byte
}

func NewOtpContext() *OtpContext {
	return &OtpContext{bytes: []byte{}}
}

func OtpContextFromBytes(b []byte) *OtpContext {
	return &OtpContext{bytes: b}
}

func (c *OtpContext) Bytes() []byte {
	return c.bytes
}

func (c *OtpContext) IsEmpty() bool {
	return len(c.bytes) == 0
}

type OtpContextBuilder struct {
	fields map[string]string
}

func NewOtpContextBuilder() *OtpContextBuilder {
	return &OtpContextBuilder{
		fields: make(map[string]string),
	}
}

func (b *OtpContextBuilder) IP(ip string) *OtpContextBuilder {
	b.setField("ip", ip)
	return b
}

func (b *OtpContextBuilder) Device(deviceID string) *OtpContextBuilder {
	b.setField("device", deviceID)
	return b
}

func (b *OtpContextBuilder) Session(session string) *OtpContextBuilder {
	b.setField("session", session)
	return b
}

func (b *OtpContextBuilder) Origin(origin string) *OtpContextBuilder {
	normalized := normalizeOrigin(origin)
	b.setField("origin", normalized)
	return b
}

// Region binds the OTP to a coarse, application-defined area label such as
// "id-lmg-bluluk" or "us-nyc-midtown". This is intentionally more stable
// than raw latitude/longitude for production OTP flows.
func (b *OtpContextBuilder) Region(region string) *OtpContextBuilder {
	b.setField("region", normalizeContextLabel(region))
	return b
}

// GeoBucket binds the OTP to a coarse location bucket generated by the
// application, such as a grid cell or geohash prefix chosen by the caller.
func (b *OtpContextBuilder) GeoBucket(bucket string) *OtpContextBuilder {
	b.setField("geo_bucket", normalizeContextLabel(bucket))
	return b
}

// DistanceClass binds the OTP to a coarse proximity class. Invalid values are
// ignored to preserve builder ergonomics and compatibility.
func (b *OtpContextBuilder) DistanceClass(class string) *OtpContextBuilder {
	normalized := normalizeDistanceClass(class)
	if normalized == "" {
		return b
	}
	b.setField("distance_class", normalized)
	return b
}

func (b *OtpContextBuilder) Custom(key, value string) *OtpContextBuilder {
	if len(key) <= maxContextFieldLen {
		b.setField("x-"+key, value)
	}
	return b
}

func (b *OtpContextBuilder) Build() *OtpContext {
	keys := make([]string, 0, len(b.fields))
	for k := range b.fields {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var buf bytes.Buffer
	for _, k := range keys {
		buf.WriteString(k)
		buf.WriteByte('=')
		buf.WriteString(b.fields[k])
		buf.WriteByte(0)
	}

	return &OtpContext{bytes: buf.Bytes()}
}

func normalizeOrigin(origin string) string {
	origin = strings.TrimSpace(origin)
	origin = strings.ToLower(origin)

	if idx := strings.Index(origin, "#"); idx != -1 {
		origin = origin[:idx]
	}

	if idx := strings.Index(origin, "?"); idx != -1 {
		origin = origin[:idx]
	}

	if idx := strings.Index(origin, "://"); idx != -1 {
		scheme := origin[:idx]
		rest := origin[idx+3:]

		if idx2 := strings.Index(rest, "/"); idx2 != -1 {
			rest = rest[:idx2]
		}

		origin = scheme + "://" + rest
	}

	origin = strings.TrimSuffix(origin, "/")
	return origin
}

func normalizeContextLabel(value string) string {
	return strings.ToLower(strings.TrimSpace(value))
}

func normalizeDistanceClass(value string) string {
	value = normalizeContextLabel(value)
	if _, ok := allowedDistanceClasses[value]; !ok {
		return ""
	}
	return value
}

func (b *OtpContextBuilder) setField(key, value string) {
	if len(value) <= maxContextFieldLen {
		b.fields[key] = value
	}
}
